### ISSUE TITLE
feature request: Connect Button extension

### ISSUE THREAD

**Issue by heiningair** [labscommunity/arweave-wallet-kit#12]
Hi,

First of all, the arweave-wallet-kit so far is awesome. It helps a lot with setting up the necessary tools needed for an arweave app, which is awesome!

Sadly, the ConnectButton component is pretty much unusable for me (and probably others too) since it does not "really" let you customize the style and other props much. It would be great to have at least the option to give it another button text and also to let a user configure the overall font-family for the modal in order to make it compatible with the style of the rest of your application. 

Is this something that is planned already?

What are the collaboration guidlines for this project? Can everybody just create a pull request here?

thx

**Comment by 7i7o** [comment]
Hi @heiningair
Thank you for expressing your interest in our project!

We truly appreciate your enthusiasm and welcome your contributions to enhance the project and benefit the community. It's important to note that we are currently focusing on developing a more modular approach for Arweave Wallet Kit. This involves improving support for various frameworks and simplifying the process of adding support for additional wallets.

Feel free to contribute in any way you believe will enhance the project and align with our goals. Your involvement is valuable, and we look forward to seeing how your contributions can positively impact our initiative.

**Comment by heiningair** [comment]
Thanks @7i7o I appreciate that! 

Awesome that you guys are already working on a more modular approach. Can`t wait to see that.

**Comment by 7i7o** [comment]
Issue addressed in #13
